### ISSUE TITLE
mysql-connector-python package is broken

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#102]
Originally reported by: **Stanislav Bashkyrtsev (Bitbucket: [ctapobep](https://bitbucket.org/ctapobep), GitHub: [ctapobep](https://github.com/ctapobep))**

----------------------------------------

All the links for [mysql-connector-python package](https://pypi.python.org/simple/mysql-connector-python/) are either broken or lead to HTML pages. So when I try running:
```
sudo pip install mysql-connector-python
```

I get error:
```
Downloading/unpacking mysql-connector-python
  Getting page https://pypi.python.org/simple/mysql-connector-python/
  URLs to search for versions for mysql-connector-python:
  * https://pypi.python.org/simple/mysql-connector-python/
  Analyzing links from page https://pypi.python.org/simple/mysql-connector-python/
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.0.10.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.0.12.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.0.5.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.0.6b2.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.0.7.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.0.9.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-1.1.4.zip (from https://pypi.python.org/simple/mysql-connector-python/) because it is externally hosted.
    Skipping link http://dev.mysql.com/doc/connector-python/en/index.html (from https://pypi.python.org/simple/mysql-connector-python/); unknown archive format: .html
    Skipping link http://dev.mysql.com/downloads/connector/python/ (from https://pypi.python.org/simple/mysql-connector-python/); not a file
    Skipping link http://dev.mysql.com/usingmysql/python/ (from https://pypi.python.org/simple/mysql-connector-python/); not a file
  Could not find any downloads that satisfy the requirement mysql-connector-python
  Some externally hosted files were ignored (use --allow-external mysql-connector-python to allow).
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for mysql-connector-python
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5-py2.7.egg/pip/commands/install.py", line 270, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5-py2.7.egg/pip/req.py", line 1157, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5-py2.7.egg/pip/index.py", line 285, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for mysql-connector-python
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/102

**Comment by ewdurbin** [comment]
unfortunately the maintainers of the `mysql-connector-python` package will need to address this.
