### ISSUE TITLE
Pip cannot connect to

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#202]
Originally reported by: **Joe Borg (Bitbucket: [jdborg](https://bitbucket.org/jdborg), GitHub: [jdborg](https://github.com/jdborg))**

----------------------------------------

```
#!python
$ export http_proxy=http://localhost:3128
$ export https_proxy=http://localhost:3128
$ sudo pip -v install scipy --proxy http://localhost:3128

Downloading/unpacking scipy
  Could not fetch URL https://pypi.python.org/simple/scipy/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/scipy/ (Caused by <class 'httplib.BadStatusLine'>: '')
  Will skip URL https://pypi.python.org/simple/scipy/ when looking for download links for scipy
  Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ (Caused by <class 'httplib.BadStatusLine'>: '')
  Will skip URL https://pypi.python.org/simple/ when looking for download links for scipy
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/scipy/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/scipy/ (Caused by <class 'httplib.BadStatusLine'>: '')
  Will skip URL https://pypi.python.org/simple/scipy/ when looking for download links for scipy
  Could not find any downloads that satisfy the requirement scipy
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for scipy
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for scipy

Storing debug log for failure in /root/.pip/pip.log

```

But curl is fine

```
#!bash

$ curl https://pypi.python.org/simple/scipy/
<html><head><title>Links for scipy</title><meta name="api-version" value="2" /></head><body><h1>Links for scipy</h1><a href="../../packages/2.7/s/scipy/scipy-0.13.3-cp27-none-macosx_10_6_intel.whl#md5=4bc791c9f37645380cab2843e63d18db" rel="internal">scipy-0.13.3-cp27-none-macosx_10_6_intel.whl</a><br/>
<a href="../../packages/3.3/s/scipy/scipy-0.13.3-cp33-cp33m-macosx_10_6_intel.whl#md5=ca634955b1757fe5e22c6a8a035bb328" rel="internal">scipy-0.13.3-cp33-cp33m-macosx_10_6_intel.whl</a><br/>
<a href="../../packages/3.4/s/scipy/scipy-0.13.3-cp34-cp34m-macosx_10_6_intel.whl#md5=0042a2e09d1632b47ed4fdb411cf9821" rel="internal">scipy-0.13.3-cp34-cp34m-macosx_10_6_intel.whl</a><br/>
<a href="../../packages/cp27/s/scipy/scipy-0.10.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=310a518b189f32116da85e1762126b1a" rel="internal">scipy-0.10.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp27/s/scipy/scipy-0.11.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=b385333496b8b25a5782c2a7a35413d3" rel="internal">scipy-0.11.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp27/s/scipy/scipy-0.12.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=8230187d0f2580bbdf78fa1b56b01087" rel="internal">scipy-0.12.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp27/s/scipy/scipy-0.13.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=0b3c405ba421f43cf97837c5aa172515" rel="internal">scipy-0.13.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp27/s/scipy/scipy-0.14.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=d3728a6d43c3265003db3781cbd4660f" rel="internal">scipy-0.14.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp33/s/scipy/scipy-0.13.0-cp33-cp33m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=d451fff29fd3d7aa501d6206bfed15f2" rel="internal">scipy-0.13.0-cp33-cp33m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp33/s/scipy/scipy-0.14.0-cp33-cp33m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=0ff3c20cb8e9c5c38e5a18cda3178ca7" rel="internal">scipy-0.14.0-cp33-cp33m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp34/s/scipy/scipy-0.13.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=dcd20dad203d301f0b5ec7aa0bb49aa3" rel="internal">scipy-0.13.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/cp34/s/scipy/scipy-0.14.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl#md5=de679794f46812c784845835371539f4" rel="internal">scipy-0.14.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.10.0.tar.gz#md5=e357c08425fd031dce63bc4905789088" rel="internal">scipy-0.10.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.10.0.zip#md5=d1a4242266739433dcfe2096b0ab4007" rel="internal">scipy-0.10.0.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.10.1.tar.gz#md5=6ad976549e22e04ca93e70cf55b70a22" rel="internal">scipy-0.10.1.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.10.1.zip#md5=4156cc1b765eb186de9518a94b6c3518" rel="internal">scipy-0.10.1.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.11.0.tar.gz#md5=842c81d35fd63579c41a8ca21a2419b9" rel="internal">scipy-0.11.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.11.0.zip#md5=40b700ddde9ddab643b640fff7a9d753" rel="internal">scipy-0.11.0.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.12.0.tar.gz#md5=8fb4da324649f655e8557ea92b998786" rel="internal">scipy-0.12.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.12.0.zip#md5=e4b9f3cb2e965fc8751faedfb9164d08" rel="internal">scipy-0.12.0.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.12.1.tar.gz#md5=906278290152fedfe79029371ca584a5" rel="internal">scipy-0.12.1.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.12.1.zip#md5=3f23065fc45152c92c3588dad2f20c62" rel="internal">scipy-0.12.1.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.0.tar.gz#md5=ffa1e9bfd2bbdf3f17f4cf8139084098" rel="internal">scipy-0.13.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.0.zip#md5=bd588ce8255e4d5427b5b19e9da2d4c7" rel="internal">scipy-0.13.0.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.1.tar.gz#md5=e082fe358a2b39cff235e5af4240f5a5" rel="internal">scipy-0.13.1.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.1.zip#md5=485411032b02583b4eb63caec6f2a916" rel="internal">scipy-0.13.1.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.2.tar.gz#md5=fcd110802b0bf3505ba567cf831566e1" rel="internal">scipy-0.13.2.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.2.zip#md5=9befa30e546fba762a0c1695a509f731" rel="internal">scipy-0.13.2.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.3.tar.gz#md5=0547c1f8e8afad4009cc9b5ef17a2d4d" rel="internal">scipy-0.13.3.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.13.3.zip#md5=20ff3a867cc5925ef1d654aed2ff7e88" rel="internal">scipy-0.13.3.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.14.0.tar.gz#md5=d7c7f4ccf8b07b08d6fe49d5cd51f85d" rel="internal">scipy-0.14.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.14.0.zip#md5=7ee4fa9e756bab6b46b79f77c821cb68" rel="internal">scipy-0.14.0.zip</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.8.0.tar.gz#md5=f0bfc6141b90e6a31555b31486602251" rel="internal">scipy-0.8.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.9.0.tar.gz#md5=ebfef6e8e82d15c875a4ee6a46d4e1cd" rel="internal">scipy-0.9.0.tar.gz</a><br/>
<a href="../../packages/source/s/scipy/scipy-0.9.0.zip#md5=a37933c9e3c4fdf8d087624cd7dcb47d" rel="internal">scipy-0.9.0.zip</a><br/>
</body></html>
```

`httplib.BadStatusLine` suggests that there is a bad HTTP response code returned, but that also looks fine.

```
#!bash

$ curl -s -o /dev/null -w "%{http_code}\n" https://pypi.python.org/simple/scipy/
200
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/202

**Comment by berkerpeksag** [comment]
I don't think PyPI can do much here. I'd suggest reporting to pip developers.
