### ISSUE TITLE
StringFormat: {n:,d} -> Invalid conversion specification

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#251]
Originally reported by: **sam-s (Bitbucket: [sam-s](https://bitbucket.org/sam-s), GitHub: [sam-s](https://github.com/sam-s))**

----------------------------------------

```
#!python

Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> "{n:,d}".format(n=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid conversion specification
>>> import stringformat
>>> stringformat.init(True)
>>> "{n:,d}".format(n=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/stringformat.py", line 326, in format
    return FormattableString(self).format(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/stringformat.py", line 267, in format
    want_bytes)
  File "/usr/lib/python2.6/site-packages/stringformat.py", line 159, in _format_field
    value = value.__format__(spec)
ValueError: Invalid conversion specification
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/251

**Comment by berkerpeksag** [comment]
Please report this to https://github.com/florentx/stringformat
