### ISSUE TITLE
bitbucket-api 0.5.0 install on windows failed

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#283]
Originally reported by: **cyrduf (Bitbucket: [cyrduf](https://bitbucket.org/cyrduf), GitHub: [cyrduf](https://github.com/cyrduf))**

----------------------------------------

The bitbucket-api package can't be installed with pip or manually for windows platform:
Can you give a way to install package on windows or correct dependancies on setup script ?

Error raised even if pbs package has been installed before:

```
Requirement already satisfied (use --upgrade to upgrade): requests in h:\python2
7\lib\site-packages (from bitbucket-api)
Downloading/unpacking sh (from bitbucket-api)
  Downloading sh-1.11.tar.gz
  Running setup.py (path:c:\users\cd\appdata\local\temp\pip_build_CD\sh\setup.py
) egg_info for package sh
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\cd\appdata\local\temp\pip_build_CD\sh\setup.py", line 4, in
 <module>
        import sh
      File "sh.py", line 37, in <module>
        support." % __version__)
    ImportError: sh 1.11 is currently only supported on linux and osx. please in
stall pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\cd\appdata\local\temp\pip_build_CD\sh\setup.py", line 4, in <mo
dule>

    import sh

  File "sh.py", line 37, in <module>

    support." % __version__)

ImportError: sh 1.11 is currently only supported on linux and osx. please instal
l pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/283

**Comment by berkerpeksag** [comment]
This needs to be reported either to bitbucket-api or sh developers. PyPI and pip do not have any control on user uploaded packages.
