### ISSUE TITLE
ssl cert error when trying to install "flexget" using python pip. vcversioner

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#321]
Originally reported by: **ali raza (Bitbucket: [alirz](https://bitbucket.org/alirz), GitHub: [alirz](https://github.com/alirz))**

---

Running this on a OPENWRT based router. This has always worked in the past. Today tried to reinstall "flexget" but getting some error related to python packages

```
Collecting jsonschema>=2.0 (from flexget)
  Downloading jsonschema-2.5.1.tar.gz (50kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 53kB 512kB/s 
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/vcversioner/: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'vcversioner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for vcversioner
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-xUX8Y9/jsonschema/setup.py", line 44, in <module>
        vcversioner={"version_module_paths" : ["jsonschema/_version.py"]},
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 267, in __init__
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 312, in fetch_build_eggs
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 378, in fetch_build_egg
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 623, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vcversioner')

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xUX8Y9/jsonschema

```

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/321

**Comment by jamadden** [comment]
This appears to have been a transient issue that cannot be produced today, so I think we can close this.
