### ISSUE TITLE
"setuptools_scm" could not be found

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#322]
Originally reported by: **ali raza (Bitbucket: [alirz](https://bitbucket.org/alirz), GitHub: [alirz](https://github.com/alirz))**

---

```
Collecting tmdb3 (from flexget)
  Downloading tmdb3-0.7.2.tar.gz
Collecting path.py (from flexget)
  Downloading path.py-7.6.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for setuptools-scm
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-VwgXX3/path.py/setup.py", line 49, in <module>
        setuptools.setup(**setup_params)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 267, in __init__
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 312, in fetch_build_eggs
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 378, in fetch_build_egg
      File "/usr/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 623, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')


Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-VwgXX3/path.py

```

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/322

**Comment by ulope** [comment]
This bug also occurs when trying to install for example `pdbpp`.
As in the original report manually installing `setuptools-scm` fixes the problem.

It's however not reproducible with pip 8.1.1

So this looks like it's probably not PyPI's problem but instead another fallout from pip 8.1.2's package name normalization.

```
ulo@dhcp27 ~ ⊙ tmp-31a19272a1024fa7@3.5
○ python --version
Python 3.5.1

ulo@dhcp27 ~ ⊙ tmp-31a19272a1024fa7@3.5
○ pip list
pip (8.1.2)
setuptools (23.1.0)
wheel (0.29.0)

○ pip install pdbpp
Collecting pdbpp
  Using cached pdbpp-0.8.3.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    No local packages or download links found for setuptools_scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w9/dw430b4150jgsh1_f2cx5c8r0000gp/T/pip-build-8iqxow8t/pdbpp/setup.py", line 79, in <module>
        'install_pth_hack': install_pth_hack,
      File "/Users/ulo/.pythonz/pythons/CPython-3.5.1/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/ulo/Envs/tmp-31a19272a1024fa7/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w9/dw430b4150jgsh1_f2cx5c8r0000gp/T/pip-build-8iqxow8t/pdbpp/
```

**Comment by exhuma** [comment]
I have run into the same issue when installing both `pytest` and `pytest-xdist` and can confirm that manually installing `setuptools-scm` first solves it.

My environment:

* Ubuntu 14.04.3
* Python 3.4.3
* pip 8.1.2
* Proxied connection via hostname: `bbs-pylon.ipsw.dt.ept.lu` (see TB below)

Steps to reproduce:

* Create a new virtual environment: `pyvenv-3.4 env`
* Try installing pytest + components: `./env/bin/pip install pytest pytest-xdist`
* **Error happens here:**
```
Download error on https://pypi.python.org/simple/setuptools_scm/: hostname 'bbs-pylon.ipsw.dt.ept.lu' doesn't match either of 'www.python.org', 'docs.python.org', 'bugs.python.org', 'wiki.pytho n.org', 'hg.python.org', 'mail.python.org', 'pypi.python.org', 'packaging.python.org', 'login.python.org', 'discuss.python.org', 'us.pycon.org', 'pypi.io', 'docs.pypi.io', 'pypi.org', 'docs.pypi.or g', 'donate.pypi.org' -- Some packages may not be found!
Download error on https://pypi.python.org/simple/setuptools-scm/: hostname 'bbs-pylon.ipsw.dt.ept.lu' doesn't match either of 'www.python.org', 'docs.python.org', 'bugs.python.org', 'wiki.pytho n.org', 'hg.python.org', 'mail.python.org', 'pypi.python.org', 'packaging.python.org', 'login.python.org', 'discuss.python.org', 'us.pycon.org', 'pypi.io', 'docs.pypi.io', 'pypi.org', 'docs.pypi.or g', 'donate.pypi.org' -- Some packages may not be found!
Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: hostname 'bbs-pylon.ipsw.dt.ept.lu' doesn't match either of 'www.python.org', 'docs.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.pyt hon.org', 'mail.python.org', 'pypi.python.org', 'packaging.python.org', 'login.python.org', 'discuss.python.org', 'us.pycon.org', 'pypi.io', 'docs.pypi.io', 'pypi.org', 'docs.pypi.org', 'donate.pyp i.org' -- Some packages may not be found!
No local packages or download links found for setuptools-scm
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-pg9ufddu/pytest-xdist/setup.py", line 37, in <module>
    'Programming Language :: Python :: 3',
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/setuptools/dist.py", line 314, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/users/michel/tmp/env/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 610, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')
```

Solved by using the following sequence:

* Create a new virtual environment: `pyvenv-3.4 env`
* Installing setuptools: `./env/bin/pip install setuptools-scm`
* Try installing pytest + components: `./env/bin/pip install pytest pytest-xdist`

**Comment by dstufft** [comment]
Looks like you have some sort of proxy between you and PyPI that's preventing download.

**Comment by wsanchez** [comment]
I'm running into a similar problem with Python 3.6 on OS X:

```
[tool:~] wsanchez$ python3.6 -m virtualenv /tmp/t
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /tmp/t/bin/python3.6
Also creating executable in /tmp/t/bin/python
Installing setuptools, pip, wheel...done.
[tool:~] wsanchez$ /tmp/t/bin/pip install Twisted
Collecting Twisted
  Using cached Twisted-16.5.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3q/m6cdbs6j6sl24dqmbhw1bpfr0000gp/T/pip-build-wvvcrbce/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/t/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/tmp/t/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/tmp/t/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/tmp/t/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/tmp/t/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/tmp/t/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/tmp/t/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3q/m6cdbs6j6sl24dqmbhw1bpfr0000gp/T/pip-build-wvvcrbce/Twisted/
[tool:~] wsanchez$ /tmp/t/bin/pip install incremental
Collecting incremental
  Using cached incremental-16.10.1-py2.py3-none-any.whl
Installing collected packages: incremental
Successfully installed incremental-16.10.1
[tool:~] wsanchez$ 
```

**Comment by wsanchez** [comment]
This works with Python 3.5, but not with 3.6, both from the python.org installers.
I don't think there are any proxies in play.

**Comment by dstufft** [comment]
Does anything change if you install certifi?

**Comment by wsanchez** [comment]
Yes, that works…

**Comment by wsanchez** [comment]
Looks like it's not enough to install it system-wide; needs to be in the venv, FWIW.

**Comment by dstufft** [comment]
Did 3.5 link against system OpenSSL and 3.6 link against a bundled copy?

**Comment by wsanchez** [comment]
Correct

**Comment by dstufft** [comment]
So 3.5 is getting certificates from the OS and 3.6 is not. Pip itself works because we bundle our own certificates but setup_requires is handled by setuptools and it relies on the OS unless you install certifi.

**Comment by lucas1993ch** [comment]
thanks a lot ,it work if I upgrade the pip to 8.1.2

**Comment by FedericoRessi** [comment]
This problem looks related to packages that uses setup_requires parameter in setup.py. I think this issue is related with this one: https://github.com/pytest-dev/pytest-xdist/issues/136#issuecomment-293016404

**Comment by di** [comment]
This is not a problem with PyPI.
