### ISSUE TITLE
cx_Oracle not a valid Win32 application

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#328]
Originally reported by: **Andrew Kwok (Bitbucket: [andrew_kwok](https://bitbucket.org/andrew_kwok), GitHub: Unknown)**

----------------------------------------

I downloaded cx_Oracle-5.2-11g.win-amd64-py2.7.exe
from https://pypi.python.org/pypi/cx_Oracle/5.2 and installed
it on my window system (Windows 7 Enterprise 64 bit).  The installation
ran smoothly.  Then I copied the dll cx_Oracle.pyd to WinPython environment.
Then I ran my python application.  It reported cx_Oracle was not a valid Win32 application.
Here is a screen dump showing the error message:

Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>> import db_trans_manager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "db_trans_manager.py", line 10, in <module>
    import cx_Oracle
ImportError: DLL load failed: %1 is not a valid Win32 application.
>>>
     --------

Here is another screen dump showing the cmd shell was finding the correct WinPython
python:

C:\ANDREW\projects_tasks\combine_spreadsheet_loader_winpython>which python
/cygdrive/c/ANDREW/projects_tasks/combine_spreadsheet_loader_winpython/python-2.
7.10.amd64/python

C:\ANDREW\projects_tasks\combine_spreadsheet_loader_winpython>
    -----

Please investigate if the dll was really had problem.

Thanks,

Andrew K

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/328

**Comment by ewdurbin** [comment]
please file with the cx_Oracle package directly.
