### ISSUE TITLE
pypi search (and pip search) failing

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#338]
Originally reported by: **Kerrigan Joseph (Bitbucket: [karjaneth](https://bitbucket.org/karjaneth), GitHub: [karjaneth](https://github.com/karjaneth))**

----------------------------------------

Trying to search for packages on pypi.python.org gives an error message.
e.g. https://pypi.python.org/pypi?%3Aaction=search&term=something&submit=search
shows the error in the first attachment

Trying to search with pip gives the following error:

```
#!exception

$ pip3 search something
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/search.py", line 40, in run
    pypi_hits = self.search(query, index_url)
  File "/usr/lib/python3/dist-packages/pip/commands/search.py", line 54, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1098, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1428, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1140, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1156, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1327, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 657, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.KeyError'>:'hits'">

Storing debug log for failure in /tmp/tmpbugd69_s
```

I believe I was able to search yesterday, so something must have changed/broken since then.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/338

**Comment by ewdurbin** [comment]
this is resolved.
