### ISSUE TITLE
Removed (stale) packages still show up in PyPI search results

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#352]
Originally reported by: **Pavel Paulau (Bitbucket: [pavelpaulau](https://bitbucket.org/pavelpaulau), GitHub: Unknown)**

----------------------------------------

It looks like search results are cached somewhere (Fastly?).

```
$ ./e/bin/pip search letsencrypt
letsencrypt-nginx-version - Nginx plugin for Let's Encrypt client
letsencrypt-nginx-twine   - Nginx plugin for Let's Encrypt client
letsencrypt-nginx-zzz     - Nginx plugin for Let's Encrypt client
letsencrypt               - Let's Encrypt client
letsencrypt-nginx         - Nginx plugin for Let's Encrypt client
letsencrypt-nginx-test    - Nginx plugin for Let's Encrypt client
letsencrypt-nginx-pypi    - Nginx plugin for Let's Encrypt client
```
```
$ ./e/bin/pip install --pre --verbose letsencrypt-nginx-test
Downloading/unpacking letsencrypt-nginx-test
  Could not fetch URL https://pypi.python.org/simple/letsencrypt-nginx-test/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/letsencrypt-nginx-test/ when looking for download links for letsencrypt-nginx-test
  Could not fetch URL https://pypi.python.org/simple/letsencrypt-nginx-test/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/letsencrypt-nginx-test/ when looking for download links for letsencrypt-nginx-test
  Could not find any downloads that satisfy the requirement letsencrypt-nginx-test
Cleaning up...
No distributions at all found for letsencrypt-nginx-test
Exception information:
Traceback (most recent call last):
  File "/tmp/e/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/e/local/lib/python2.7/site-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/e/local/lib/python2.7/site-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/tmp/e/local/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for letsencrypt-nginx-test

Storing debug log for failure in /home/pavel/.pip/pip.log
```

```
$ cat /home/pavel/.pip/pip.log
------------------------------------------------------------
./e/bin/pip run on Wed Nov  4 21:14:01 2015
Downloading/unpacking letsencrypt-nginx-test
  Getting page https://pypi.python.org/simple/letsencrypt-nginx-test/
  Could not fetch URL https://pypi.python.org/simple/letsencrypt-nginx-test/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/letsencrypt-nginx-test/ when looking for download links for letsencrypt-nginx-test
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for letsencrypt-nginx-test:
  * https://pypi.python.org/simple/letsencrypt-nginx-test/
  Getting page https://pypi.python.org/simple/letsencrypt-nginx-test/
  Could not fetch URL https://pypi.python.org/simple/letsencrypt-nginx-test/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/letsencrypt-nginx-test/ when looking for download links for letsencrypt-nginx-test
  Could not find any downloads that satisfy the requirement letsencrypt-nginx-test
Cleaning up...
No distributions at all found for letsencrypt-nginx-test
Exception information:
Traceback (most recent call last):
  File "/tmp/e/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/e/local/lib/python2.7/site-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/e/local/lib/python2.7/site-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/tmp/e/local/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for letsencrypt-nginx-test
```

```
$ curl -I https://pypi.python.org/pypi/letsencrypt-nginx-test/0.1.0.dev0
HTTP/1.1 404 Not Found
Server: nginx/1.8.0
Content-Type: text/html
ETag: "54d6913d-6d9f"
Via: 1.1 varnish
Content-Length: 28063
Accept-Ranges: bytes
Date: Thu, 05 Nov 2015 05:08:56 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-iad2122-IAD, cache-sjc3121-SJC
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1446700136.595493,VS0,VE96
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/352

**Comment by ewdurbin** [comment]
this is resolved by https://github.com/pypa/pypi-legacy/commit/6e96e374004ca9a854ca541b1b90144d6e72ac92
