### ISSUE TITLE
PyCharm can not install BeautifulSoup package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#367]
Originally reported by: **Daniel Rabinovich (Bitbucket: [daniel_rabinovich](https://bitbucket.org/daniel_rabinovich), GitHub: Unknown)**

----------------------------------------

I am very new in Python. Can anybody suggest a solution.
Thanks in advance
Daniel

![Captura.JPG](https://bitbucket.org/repo/j9KaaX/images/727122859-Captura.JPG)

Collecting BeautifulSoup
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\daniel\AppData\Local\Temp\pycharm-packaging0.tmp\BeautifulSoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\daniel\AppData\Local\Temp\pycharm-packaging0.tmp\BeautifulSoup

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/367

**Comment by ewdurbin** [comment]
please file with the PyCharm project directly.
