### ISSUE TITLE
pip search for "test", "ssh", or "remote" result in exception; return error page on pypi website

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#421]
Originally reported by: **Timothy Yandl (Bitbucket: [tyandl](https://bitbucket.org/tyandl), GitHub: [tyandl](https://github.com/tyandl))**

----------------------------------------

searching for any of: "test", "ssh", "remote" with pip commandline in mac or on windows throws an exception (included below).
pip version: pip 8.1.0 from /usr/local/lib/python3.5/site-packages (python 3.5)
python version: Python 3.5.1

the same keywords search on https://pypi.python.org/pypi result in a redirect to an error page. error page has url: "https://pypi.python.org/pypi?%3Aaction=search&term=test&submit=search"

browser console indicates: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

$ pip3 search test

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1091, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1431, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 767, in request
    return self.parse_response(response.raw)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1321, in parse_response
    return u.close()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 654, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.KeyError'>:'_pypi_hidden'">

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/421

**Comment by philbert** [comment]
I can add all of these search terms that break in the same way:
"req", "requ", "reque", "reques", "request", "requests"

Running Cygwin64 on Windows7 with
Python 3.4.3
pip 8.1.2 from /usr/lib/python3.4/site-packages/pip-8.1.2-py3.4.egg (python 3.4)

Current pip packages installed:
```
10:42 query_api master → pip3 list
pip (8.1.2)
requests (2.10.0)
setuptools (15.2)
```

Actual error:
```
10:38 query_api master → pip3 search requests
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pip-8.1.2-py3.4.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.4/site-packages/pip-8.1.2-py3.4.egg/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/usr/lib/python3.4/site-packages/pip-8.1.2-py3.4.egg/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1098, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1437, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/site-packages/pip-8.1.2-py3.4.egg/pip/download.py", line 767, in request
    return self.parse_response(response.raw)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1327, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 657, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.KeyError'>:'_pypi_hidden'">
```

**Comment by philbert** [comment]
Also on OSX 10.10.5, python 3.5.0, pip 8.1.1 

```
(python3_dev)12:21:06 ~  » pip search req                                                                                                                  2 ↵
Exception:
Traceback (most recent call last):
  File "/Users/philbert/.virtualenvs/python3_dev/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Users/philbert/.virtualenvs/python3_dev/lib/python3.5/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/Users/philbert/.virtualenvs/python3_dev/lib/python3.5/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1091, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1431, in __request
    verbose=self.__verbose
  File "/Users/philbert/.virtualenvs/python3_dev/lib/python3.5/site-packages/pip/download.py", line 767, in request
    return self.parse_response(response.raw)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1321, in parse_response
    return u.close()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 654, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.KeyError'>:'_pypi_hidden'">
```

**Comment by ewdurbin** [comment]
resolved with https://github.com/pypa/pypi-legacy/commit/b269ae531d02c8f78be49b11f096f968e716edcb and https://github.com/pypa/pypi-legacy/commit/da987d855c862433c00aed07008db0efa893cdc9
