### ISSUE TITLE
'table' and all substrings of 'table' of length > 2 are unsearchable on pypi and via pip.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#425]
Originally reported by: **Weston Odom (Bitbucket: [wtodom](https://bitbucket.org/wtodom), GitHub: [wtodom](https://github.com/wtodom))**

----------------------------------------

I wanted to search for a good table printing library and was surprised to find that 'table' and all substrings of length greater than 2 are unsearchable. This shows itself on the web (https://pypi.python.org/pypi) and via `pip search`. I've pasted an example of the pip error below.

The only reason I can think of that this would be the case is if it's an extremely inelegant sql injection prevention mechanism. However, some of the substrings (not to mention 'table' itself) are reasonable searches.

```
(env)➜  alert-convert git:(master) ✗ pip search table
Exception:
Traceback (most recent call last):
  File "/Users/weston/repositories/alert-convert/env/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/weston/repositories/alert-convert/env/lib/python2.7/site-packages/pip/commands/search.py", line 40, in run
    pypi_hits = self.search(query, index_url)
  File "/Users/weston/repositories/alert-convert/env/lib/python2.7/site-packages/pip/commands/search.py", line 54, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: "<type 'exceptions.KeyError'>:'_pypi_hidden'">

Storing debug log for failure in /Users/weston/.pip/pip.log
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/425

**Comment by ewdurbin** [comment]
resolved with https://github.com/pypa/pypi-legacy/commit/b269ae531d02c8f78be49b11f096f968e716edcb and https://github.com/pypa/pypi-legacy/commit/da987d855c862433c00aed07008db0efa893cdc9
