### ISSUE TITLE
Pickle error on running primefac in python

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#429]
Originally reported by: **liujeffqi (Bitbucket: [liujeffqi](https://bitbucket.org/liujeffqi), GitHub: [liujeffqi](https://github.com/liujeffqi))**

----------------------------------------

I am learning number theory right now, i am trying to use N to find p and q for RSA

I am using primefac package from python

https://pypi.python.org/pypi/primefac

i test it, it works pretty well on some number i testing but not all for example

617686377693546512802931776089 (28 digits) will give me errors below 617686377693546512802931776085 will be perfectly fine.

other large number i tried will give me error too and some will work fine.

I am running python 2.7 on windows 10 the command to run i used cmd and enter python -m primefac <number>

error message:

`File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main  
"__main__", fname, loader, pkg_name)  
File "C:\Python27\lib\runpy.py", line 72, in _run_code  
exec code in run_globals  
File "C:\Python27\lib\site-packages\primefac.py", line 836, in <module>  
for p in primefac(n, trial_limit=(n if tr == "inf" else tr), rho_rounds=rr,         verbose=veb, methods=methods):  
File "C:\Python27\lib\site-packages\primefac.py", line 677, in primefac  
f = multifactor(n, methods=methods, verbose=verbose)  
File "C:\Python27\lib\site-packages\primefac.py", line 596, in multifactor  
for p in procs: p.start()  
File "C:\Python27\lib\multiprocessing\process.py", line 130, in start  
self._popen = Popen(self)  
File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__  
dump(process_obj, to_child, HIGHEST_PROTOCOL)  
File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump  
ForkingPickler(file, protocol).dump(obj)  
File "C:\Python27\lib\pickle.py", line 224, in dump  
self.save(obj)  
File "C:\Python27\lib\pickle.py", line 331, in save  
self.save_reduce(obj=obj, *rv)  
File "C:\Python27\lib\pickle.py", line 425, in save_reduce  
save(state)  
File "C:\Python27\lib\pickle.py", line 286, in save  
f(self, obj) # Call unbound method with explicit self  
File "C:\Python27\lib\pickle.py", line 655, in save_dict  
self._batch_setitems(obj.iteritems())  
File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems  
save(v)  
File "C:\Python27\lib\pickle.py", line 286, in save  
f(self, obj) # Call unbound method with explicit self  
File "C:\Python27\lib\pickle.py", line 754, in save_global  
(obj, module, name))  
pickle.PicklingError: Can't pickle <function factory at 0x0000000002D32278>:     it's not found as __main__.factory  
Traceback (most recent call last):  
File "<string>", line 1, in <module>  
File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main  
self = load(from_parent)  
File "C:\Python27\lib\pickle.py", line 1384, in load  
C:\Users\liuje>    return Unpickler(file).load()  
File "C:\Python27\lib\pickle.py", line 864, in load  
dispatch[key](self)  
File "C:\Python27\lib\pickle.py", line 886, in load_eof  
raise EOFError  
EOFError`

I don't know how to contact the author for this package, so i post it here. 

if anyone can forward it to the author could be great 

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/429

**Comment by ewdurbin** [comment]
please file this issue with the primefac project directly.
