### ISSUE TITLE
wfastcgi + flask + IIS 8

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#443]
Originally reported by: **Darren Chuck (Bitbucket: [chuckmo8](https://bitbucket.org/chuckmo8), GitHub: [chuckmo8](https://github.com/chuckmo8))**

----------------------------------------

Environment: 
* python 3.5.1 64-bit on Windows 2012
* wfastcgi 2.2
* flask 0.10.1
* IIS 8

After setting up web.config, we get the following error:

```
#!text

Error occurred while reading WSGI handler: Traceback (most recent call last): 
File "c:\python\python35\lib\site-packages\wfastcgi.py", line 779, 
in main env, handler = read_wsgi_handler(response.physical_path) 
File "c:\python\python35\lib\site-packages\wfastcgi.py", line 621, 
in read_wsgi_handler handler = get_wsgi_handler(os.getenv('WSGI_HANDLER')) 
File "c:\python\python35\lib\site-packages\wfastcgi.py", line 594, 
in get_wsgi_handler handler = handler() 
TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response' StdOut: StdErr: 
```

Is it because of compatibility or have we wrongly configured?

The web.config file:

```
#!xml

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appSettings>
    <add key="WSGI_HANDLER" value="app.app()" />
    <add key="PYTHONPATH" value="D:\python\FlaskWebProject1;D:\python\FlaskWebProject1\FlaskWebProject1\mymodule\" />
    <add key="WSGI_LOG" value="D:\python\Logs\my_app.log" />
  </appSettings>
  <system.webServer>
    <!--<handlers accessPolicy="Read, Execute, Script" />-->
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      <add name="Python FastCGI" 
	   path="*" 
	   verb="*" 
	   modules="FastCgiModule" 
	   scriptProcessor="C:\python\python35\python.exe|c:\python\python35\lib\site-packages\wfastcgi.py" 
	   resourceType="Unspecified" 
	   requireAccess="Script" />
    </handlers>
    <rewrite>
      <rules>
        <rule name="Static Files" stopProcessing="true">
          <conditions>
            <add input="true" pattern="false" />
          </conditions>
        </rule>
        <rule name="Configure Python" stopProcessing="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_URI}" pattern="^/static/.*" ignoreCase="true" negate="true" />
          </conditions>
          <action type="Rewrite"
                  url="handler.fcgi/{R:1}"
                  appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/443

**Comment by ewdurbin** [comment]
although i am unsure what project to file this issue with, it should be brought to the attention of one or more of the involved software projects.
