### ISSUE TITLE
Bad DOAP entry for munge

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#467]
Originally reported by: **FliesLikeABrick (Bitbucket: [FliesLikeABrick](https://bitbucket.org/FliesLikeABrick), GitHub: [FliesLikeABrick](https://github.com/FliesLikeABrick))**

---

the munge package has a bad DOAP entry.  The "description" field seems to be a tuple instead of a string, and this causes at least certain pip versions (confirmed on python2.7 and 3.4) to fail:

Collecting munge

  Using cached munge-0.1.7.tar.gz

```
Complete output from command python setup.py egg_info:

running egg_info

creating pip-egg-info/munge.egg-info

writing dependency_links to pip-egg-info/munge.egg-info/dependency_links.txt

writing top-level names to pip-egg-info/munge.egg-info/top_level.txt

writing pip-egg-info/munge.egg-info/PKG-INFO

('\n# munge\n\ndata manipulation client / library\n\n',)

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-jao5e2yv/munge/setup.py", line 26, in <module>

    zip_safe=False

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 186, in run

    writer(self, ep.name, os.path.join(self.egg_info, ep.name))

  File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 397, in write_pkg_info

    metadata.write_pkg_info(cmd.egg_info)

  File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info

    self.write_pkg_file(pkg_info)

  File "/usr/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file

    long_desc = rfc822_escape(self.get_long_description())

  File "/usr/lib/python3.4/distutils/util.py", line 471, in rfc822_escape

    lines = header.split('\n')

AttributeError: 'tuple' object has no attribute 'split'



----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jao5e2yv/munge/

You can even see this on the pypi page for munge at https://pypi.python.org/pypi/munge , that the description shows the typle "(‘n# mungenndata manipulation client / librarynn’,)"

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/467

**Comment by jamadden** [comment]
munge has since been updated to version 0.4.0 and no longer shows this issue.
