### ISSUE TITLE
Regarding Installing pypi newspaper in python app(virtual env)

### ISSUE THREAD

**Issue by ankitdilip** [pypa/pypi-legacy#618]
please do help me to resolve the following error with reference to above subject:

error as follows:
Failed building wheel for Pillow
  Running setup.py clean for Pillow
  Running setup.py bdist_wheel for lxml ... done
  Stored in directory: /home/adpnewsi/.cache/pip/wheels/4e/32/96/54e578d0c5bada8d08c2b035be341500a2f93a83eb7a797d0e
Successfully built lxml
Failed to build Pillow
Installing collected packages: six, requests, tldextract, cssselect, Pillow, python-dateutil, jieba, PyYAML, nltk, lxml, feedfinder2, feedparser, newspaper
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Rolling back uninstall of six
Exception:
Traceback (most recent call last):
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/adpnewsi/newsapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/adpnewsi/newsapp/lib/python2.7/site-packages/six-1.10.0.dist-info/METADATA'

**Comment by Carreau** [comment]
Thank you for your report. However, this tracker is only for issues with the software that runs pypi.python.org itself. It is not for the software distributed there. The developers here cannot help you with problems in third-party software.

If you are installing [newspaper](https://pypi.python.org/pypi/newspaper), see their bug tracker:  https://github.com/codelucas/newspaper/

**Comment by berkerpeksag** [comment]
Matthias is correct, please use the project's issue tracker to report your problem. Thank you!
