### ISSUE TITLE
upgrading to pytest 3.3.0 passed but now can't execute pytest any more

### ISSUE THREAD

**Issue by andreyv1978** [pypa/pypi-legacy#744]
I've upgraded to pytest 3.3.0 from 3.2.1 and couldn't run pytest anymore
Uninstalling pytest and installing back not helps to resolve a problem
I've tried to make it on 3 different PC's (Windows 10) and all shows the same problem

Installation part: I had version pytest 3.2.1 works well:
```
pip install -U pytest
Collecting pytest
  Downloading pytest-3.3.0-py2.py3-none-any.whl (184kB)
    100% |################################| 184kB 1.6MB/s
Collecting pluggy<0.7,>=0.5 (from pytest)
  Downloading pluggy-0.6.0.tar.gz
Collecting six>=1.10.0 (from pytest)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest)
  Downloading py-1.5.2-py2.py3-none-any.whl (88kB)
    100% |################################| 92kB 3.7MB/s
Collecting setuptools (from pytest)
  Downloading setuptools-38.2.3-py2.py3-none-any.whl (489kB)
    100% |################################| 491kB 1.3MB/s
Collecting funcsigs; python_version < "3.0" (from pytest)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting attrs>=17.2.0 (from pytest)
  Downloading attrs-17.3.0-py2.py3-none-any.whl
Requirement already up-to-date: colorama; sys_platform == "win32" in c:\python27\lib\site-packages (from pytest)
Building wheels for collected packages: pluggy
  Running setup.py bdist_wheel for pluggy ... done
  Stored in directory: C:\Users\andrey\AppData\Local\pip\Cache\wheels\df\44\8e\e136760ae525eac46b3e3db643ef58ff1753177b5a722b0c96
Successfully built pluggy
Installing collected packages: pluggy, six, py, setuptools, funcsigs, attrs, pytest
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: py 1.4.34
    Uninstalling py-1.4.34:
      Successfully uninstalled py-1.4.34
  Found existing installation: setuptools 36.6.0
    Uninstalling setuptools-36.6.0:
      Successfully uninstalled setuptools-36.6.0
  Found existing installation: pytest 3.2.3
    Uninstalling pytest-3.2.3:
      Successfully uninstalled pytest-3.2.3
Successfully installed attrs-17.3.0 funcsigs-1.0.2 pluggy-0.6.0 py-1.5.2 pytest-3.3.0 setuptools-38.2.3 six-1.11.0
```

How to reproduce::
```
pytest or pytest --version
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\_pytest\config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "c:\python27\lib\site-packages\_pytest\config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "c:\python27\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python27\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python27\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python27\lib\site-packages\pluggy\callers.py", line 196, in _multicall
    gen.send(outcome)
  File "c:\python27\lib\site-packages\_pytest\helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "c:\python27\lib\site-packages\pluggy\callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "c:\python27\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python27\lib\site-packages\_pytest\config.py", line 942, in pytest_cmdline_parse
    self.parse(args)
  File "c:\python27\lib\site-packages\_pytest\config.py", line 1107, in parse
    self._preparse(args, addopts=addopts)
  File "c:\python27\lib\site-packages\_pytest\config.py", line 1070, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "c:\python27\lib\site-packages\pluggy\__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "c:\python27\lib\site-packages\py\_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "c:\python27\lib\site-packages\pytest_metadata\plugin.py", line 8, in <module>
    import _pytest._pluggy as pluggy
ImportError: No module named _pluggy

```

**Comment by jamadden** [comment]
Thank you for your report, but this tracker is not the right place. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with the packages distributed there. You'll need to contact the [pytest maintainers](https://github.com/pytest-dev/pytest/issues).

**Comment by jamadden** [comment]
FWIW, this looks like an issue with the `pytest_metadat` plugin you have installed. You'll need to install a more recent version (1.5.1) for [compatibility with pytest 3.3](https://github.com/davehunt/pytest-metadata/blob/master/CHANGES.rst).

**Comment by andreyv1978** [comment]
thank you, this was a problem 
installing the new pytest-metadata 1.5.1 resolve the problem
