### ISSUE TITLE
I can't install aiohttp on my computer!!

### ISSUE THREAD

**Issue by shallylan** [pypa/pypi-legacy#757]
python version:3.5.2
pip version:9.0.1

when I typed  'pip3 install aiohttp' on cmd, system would print errors to me!~following

Exception:
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python35\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python35\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python35\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python35\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\python35\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "c:\python35\lib\site-packages\pip\download.py", line 853, in _download_http_url
    stream=True,
  File "c:\python35\lib\site-packages\pip\_vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\python35\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\python35\lib\site-packages\pip\_vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python35\lib\site-packages\pip\_vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\python35\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\python35\lib\site-packages\pip\_vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "c:\python35\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "c:\python35\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 248, in _get_conn
    if conn and is_connection_dropped(conn):
  File "c:\python35\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\connection.py", line 34, in is_connection_dropped
    return select([sock], [], [], 0.0)[0]
TypeError: select() takes from 2 to 3 positional arguments but 4 were given

![image](https://user-images.githubusercontent.com/35263857/34724427-ba88b3ba-f588-11e7-8bf8-c400cc396821.png)

**Comment by shallylan** [comment]
WIN 10

**Comment by jamadden** [comment]
Thank you for your report, but unfortunately this is not the place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It can’t help with issues with those packages, or issues with pip (which is what this looks like). You’ll need to contact the pip community. You might start with [the mailing list](http://groups.google.com/group/python-virtualenv) before trying [the issue tracker](https://github.com/pypa/pip/issues). 

Good luck (that’s a very surprising exception)!

**Comment by shallylan** [comment]
thank u~!
