### ISSUE TITLE
inotify.adapters cannot be used under alpine linux

### ISSUE THREAD

**Issue by ilovemath** [pypa/pypi-legacy#770]
When I user inotify under alpine linux, it shows such error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/inotify/adapters.py", line 10, in <module>
    import inotify.calls
  File "/usr/lib/python3.6/site-packages/inotify/calls.py", line 55, in <module>
    errno = _LIB.errno
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: Symbol not found: errno

**Comment by berkerpeksag** [comment]
Thank you for the report, but the correct place to report issues with the inotify library is https://github.com/dsoprea/PyInotify This tracker is for issues with pypi.python.org website.
