### ISSUE TITLE
.pypirc stored passwords containing '%' make uploads fail

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#80]
Originally reported by: **Guido Kollerie (Bitbucket: [gkoller](https://bitbucket.org/gkoller), GitHub: [gkoller](https://github.com/gkoller))**

----------------------------------------

A password containing a '%' character and stored in ~/.pypirc results in the following error when trying to upload a package (using: python setup.py sdist upload):

```
#!python

Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    long_description=open('README').read())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/distutils/dist.py", line 941, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/distutils/dist.py", line 959, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/distutils/command/upload.py", line 50, in finalize_options
    config = self._read_pypirc()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/distutils/config.py", line 83, in _read_pypirc
    current[key] = config.get(server, key)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/configparser.py", line 790, in get
    d)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/configparser.py", line 391, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/configparser.py", line 440, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%@7)DvC'
```
Even though the password reset form on pypi happily accepted the password with the '%' character

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/80

**Comment by berkerpeksag** [comment]
This is rather a distutils issue and it has already been fixed by switching to use RawConfigParser in https://hg.python.org/cpython/rev/eae59b6bf133 I will add a test case to distutils.

**Comment by berkerpeksag** [comment]
FYI: Added a test case in https://github.com/python/cpython/commit/401c7ae9aae30349c6b146ea508e0e7699d5e299.
